### ISSUE TITLE
Startup Scripts

### ISSUE THREAD

**Issue by joshmedeski** [joshmedeski/sesh#10]
As a developer, when I start a session I want to run commands and create windows and panes so I can start my session more efficiently.

- See https://github.com/joshmedeski/t-smart-tmux-session-manager/pull/93
- Allow `tmux new -s {session} {command}`
- Or on a separate step run a startup script independently

**Comment by joebonneau** [comment]
Josh and I chatted about this a bit, and the first iteration of this implementation will be to add a new flag `--command -c` to the `connect` command to allow a user to provide a command to be run when creating a new session. This flag should be ignored if the session is already active. Eventually, we would also like to support the use of more complex startup scripts.
