### ISSUE TITLE
`sesh list`  lists the content of my $HOME

### ISSUE THREAD

**Issue by m-gris** [joshmedeski/sesh#102]
### What happened?

Hi :)

When running `sesh list`, `fzf` window pops up, but with the content of my `$HOME`, instead of my tmux sessions.

### Version

1.1.0

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by joshmedeski** [comment]
What is the full command you are running?

**Comment by m-gris** [comment]
Just running `sesh list`

after double checking, my sessions are actually listed, mixed up with all the files & dirs in my home dir...

**Comment by joshmedeski** [comment]
If you're using fzf, I recommend adding `--no-sort` to prevent fzf from changing the order of what sesh prints.
