### ISSUE TITLE
Nerd fonts dont render when i use sesh to create a new tmux session

### ISSUE THREAD

**Issue by SuyashPatil-29** [joshmedeski/sesh#103]
### What happened?

When I open a new session using sesh my nerdfonts dont render nor on my terminal nor in my neovim 

Expected - 

![image](https://github.com/joshmedeski/sesh/assets/112413583/74761184-e1e1-4822-b3a7-034989520750)

Whats happening - 

![image](https://github.com/joshmedeski/sesh/assets/112413583/0e7d773f-fbe8-4c1c-a6d3-ec914d6cc191)

On neovim -
Expected -

![image](https://github.com/joshmedeski/sesh/assets/112413583/f3556699-e841-49e8-8ba7-7031375cb374)

Whats happening - 

![image](https://github.com/joshmedeski/sesh/assets/112413583/746cda3e-8495-4391-8bc6-030bc999c663)

### Version

sesh version dev

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by SuyashPatil-29** [comment]
I am on ubuntu 22.04 and have the nerd fonts installed and working.

**Comment by joshmedeski** [comment]
Interesting, how are you calling sesh? Just directly in the terminal "sesh connect 'ai-roadmap-generator'"?

Also, if you run this outside of tmux, do you see icons?
```
sesh list -i
```

**Comment by Hugo-Persson** [comment]
I have the same issue

If I run:
```
sesh list -i | fzf-tmux -p 55%,60% \
		--no-sort --border-label ' sesh ' --prompt '⚡  ' \
		--header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
		--bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c)' \
		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
		--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list -i)'
```
I get:
<img width="1402" alt="image" src="https://github.com/joshmedeski/sesh/assets/47189713/646c5ffd-b2d4-41cb-8c1b-af16ee65c105">

If I run:
```
sesh list -i
```
I get the expected result:
<img width="283" alt="image" src="https://github.com/joshmedeski/sesh/assets/47189713/0c89be2a-75e8-408d-9a4b-743050ec9653">

**Comment by joshmedeski** [comment]
Thanks for the feedback, so it appears to break the Nerd Font rendering  only when sesh starts the tmux session.

I will do some investigation, sometimes it's related to the default terminal setting, try checking this value or setting it in your `tmux.conf`:
```
set -g default-terminal "screen-256color"
```

Other times, it can be unicode support problem, which came be set in your `tmux.conf` as well:
```
set -g utf8
setw -g utf8 on
```

Can you experiment with these settings and see if it helps? I can setup a VM and try and recreate the issue, or ask my community if anyone else uses sesh with Ubuntu, but let's see if updating the configuration can fix it first, thanks!

**Comment by Hugo-Persson** [comment]
@SuyashPatil-29 could you try restarting your computer without changing anything in your `tmux.conf`? I tried it now and fixed everything for me, maybe something weird when changing from the old plugin to the new plugin?

**Comment by SuyashPatil-29** [comment]
> Interesting, how are you calling sesh? Just directly in the terminal "sesh connect 'ai-roadmap-generator'"?
> 
> Also, if you run this outside of tmux, do you see icons?
> 
> ```
> sesh list -i
> ```

When I run 

```
sesh list -i
```

I do see my icons. Its only when I use sesh connect i get the problem. BTW I use kitty as my terminal emulator.

And yes  "sesh connect 'ai-roadmap-generator'" is what I did to directly jump into a session.

**Comment by SuyashPatil-29** [comment]
> @SuyashPatil-29 could you try restarting your computer without changing anything in your `tmux.conf`? I tried it now and fixed everything for me, maybe something weird when changing from the old plugin to the new plugin?

I did try this. I have had this issue about a month ago too. I decided to not use sesh then but now that I tried again hoping it would be fixed, its the same again.

**Comment by joshmedeski** [comment]
Have you tried a different terminal emulator? If it's just kitty that's not working that will help me in debugging what could be the root cause.

**Comment by karamanliev** [comment]
> I have the same issue on mac
> 
> If I run:
> 
> ```
> sesh list -i | fzf-tmux -p 55%,60% \
> 		--no-sort --border-label ' sesh ' --prompt '⚡  ' \
> 		--header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
> 		--bind 'tab:down,btab:up' \
> 		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
> 		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
> 		--bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c)' \
> 		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
> 		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
> 		--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list -i)'
> ```
> 
> I get: <img alt="image" width="1402" src="https://private-user-images.githubusercontent.com/47189713/329876142-646c5ffd-b2d4-41cb-8c1b-af16ee65c105.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2Nzk1MDksIm5iZiI6MTcxNTY3OTIwOSwicGF0aCI6Ii80NzE4OTcxMy8zMjk4NzYxNDItNjQ2YzVmZmQtYjJkNC00MWNiLThjMWItYWYxNmVlNjVjMTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA5MzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMDFiM2ViNmFkNThkZmEyZDUyNTc4YTc1NDM1MzBlODlkMjY1MGY4NTc1ZTU1MGRhYzQ3MjUxM2VjYjhmNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7g1wkbBc3XsI99rxjXNKTWwvS5UkftWr6DLEnBZaQOw">
> 
> If I run:
> 
> ```
> sesh list -i
> ```
> 
> I get the expected result: <img alt="image" width="283" src="https://private-user-images.githubusercontent.com/47189713/329876172-0c89be2a-75e8-408d-9a4b-743050ec9653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2Nzk1MDksIm5iZiI6MTcxNTY3OTIwOSwicGF0aCI6Ii80NzE4OTcxMy8zMjk4NzYxNzItMGM4OWJlMmEtNzVlOC00MDhkLTlhNGItNzQzMDUwZWM5NjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA5MzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMDA2MTQwMDZjYjI4MWU2MTE1NzM2OWNhMWQzODBhMzUwNzFhYzRmMTQ2Y2NhOGRiMzg2MDljZGMzN2I5M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KUUJl8vjl5Z8ZCzdhRWuMz3FsbV_Zrbkb8_NTXJ8xyw">
> 
> My fzf version is:
> 
> ```
> > fzf --version
> 0.49.0 (brew)
> ```

I can report that I have absolutely the same issue on mac and linux with wezterm terminal. Everything is updated to the latest available version.

`sesh list -i`:
<img width="298" alt="image" src="https://github.com/joshmedeski/sesh/assets/22788016/e3f11ae0-207c-4327-869f-3d2b49ccde6f">

`sesh list -i | fzf`:
<img width="453" alt="image" src="https://github.com/joshmedeski/sesh/assets/22788016/a6cf0d5f-a63c-4f4b-8302-f3dd24cbcbaf">

`sesh connect $(sesh list -i | fzf)`:
<img width="377" alt="image" src="https://github.com/joshmedeski/sesh/assets/22788016/4192d3b3-975f-444b-a196-c5dfc7799070">

**Comment by SuyashPatil-29** [comment]
> > I have the same issue on mac
> > If I run:
> > ```
> > sesh list -i | fzf-tmux -p 55%,60% \
> > 		--no-sort --border-label ' sesh ' --prompt '⚡  ' \
> > 		--header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
> > 		--bind 'tab:down,btab:up' \
> > 		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
> > 		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
> > 		--bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c)' \
> > 		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
> > 		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
> > 		--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list -i)'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I get: <img alt="image" width="1402" src="https://private-user-images.githubusercontent.com/47189713/329876142-646c5ffd-b2d4-41cb-8c1b-af16ee65c105.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2Nzk1MDksIm5iZiI6MTcxNTY3OTIwOSwicGF0aCI6Ii80NzE4OTcxMy8zMjk4NzYxNDItNjQ2YzVmZmQtYjJkNC00MWNiLThjMWItYWYxNmVlNjVjMTA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA5MzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMDFiM2ViNmFkNThkZmEyZDUyNTc4YTc1NDM1MzBlODlkMjY1MGY4NTc1ZTU1MGRhYzQ3MjUxM2VjYjhmNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7g1wkbBc3XsI99rxjXNKTWwvS5UkftWr6DLEnBZaQOw">
> > If I run:
> > ```
> > sesh list -i
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I get the expected result: <img alt="image" width="283" src="https://private-user-images.githubusercontent.com/47189713/329876172-0c89be2a-75e8-408d-9a4b-743050ec9653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2Nzk1MDksIm5iZiI6MTcxNTY3OTIwOSwicGF0aCI6Ii80NzE4OTcxMy8zMjk4NzYxNzItMGM4OWJlMmEtNzVlOC00MDhkLTlhNGItNzQzMDUwZWM5NjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDA5MzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMDA2MTQwMDZjYjI4MWU2MTE1NzM2OWNhMWQzODBhMzUwNzFhYzRmMTQ2Y2NhOGRiMzg2MDljZGMzN2I5M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KUUJl8vjl5Z8ZCzdhRWuMz3FsbV_Zrbkb8_NTXJ8xyw">
> > My fzf version is:
> > ```
> > > fzf --version
> > 0.49.0 (brew)
> > ```
> 
> I can report that I have absolutely the same issue on mac and linux with wezterm terminal. Everything is updated to the latest available version.
> 
> I've managed to make it working for me with the following tmux bind:
> 
> ```shell
> bind-key "r" run-shell "sesh connect \"$(
>     sesh list -i | fzf-tmux -p 55%,60% --layout=reverse --ansi \
>         --no-sort --border-label ' sesh ' --prompt '⚡  ' \
>         --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
>         --bind 'tab:down,btab:up' \
>         --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list -i)' \
>         --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t -i)' \
>         --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c -i)' \
>         --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z -i)' \
>         --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
>         --bind 'ctrl-d:execute(tmux kill-session -t $(echo {} | cut -c3-))+change-prompt(⚡  )+reload(sesh list -i)'
> )\""
> ```
> 
> Thanks for the great app, I love it! 👊

Thanks a ton man this works perfectly fine for me.

**Comment by joshmedeski** [comment]
Awesome, thanks everyone for the feedback and help!

**Comment by SuyashPatil-29** [comment]
sesh connect ai-roadmap-generator still does not render the nerd fonts tho @joshmedeski

**Comment by joshmedeski** [comment]
Hmm, did you confirm the Nerd Fonts render in a different terminal emulator?

**Comment by marcellmartini** [comment]
What is the NerdFonts and Tmux version?

**Comment by SuyashPatil-29** [comment]
> Hmm, did you confirm the Nerd Fonts render in a different terminal emulator?

I did try using the native ubuntu terminal and its the same thing

**Comment by SuyashPatil-29** [comment]
> What is the NerdFonts and Tmux version?

SF Mono nerd font but i also tried it with many other nerd fonts and its the same thing 

and the tmux version is 3.2a

**Comment by marcellmartini** [comment]
> > What is the NerdFonts and Tmux version?
> 
> SF Mono nerd font but i also tried it with many other nerd fonts and its the same thing
> 
> and the tmux version is 3.2a

I ask the version of Nerdfonts because some time ago the download link on the Nerdfonts page was not up to date. Downloading from the website the version font was 2.4 and download the font from GitHub repo the version was 3.2.

I checked today and the versions are equal on the website and in the GitHub repo. Would you happen to know what version you installed the Nerdfont?

I have some issues with the missing Fonts because of this version difference.

**Comment by joshmedeski** [comment]
Thanks for the feedback, @SuyashPatil-29.

I'm currently rewriting the code to make testing and debugging easier. Please bear with me as this process will take a few weeks. I'll look into this issue as soon as possible, but it's not my top priority right now since I have limited time outside my day job.

**Comment by SuyashPatil-29** [comment]
> > > What is the NerdFonts and Tmux version?
> > 
> > 
> > SF Mono nerd font but i also tried it with many other nerd fonts and its the same thing
> > and the tmux version is 3.2a
> 
> I ask the version of Nerdfonts because some time ago the download link on the Nerdfonts page was not up to date. Downloading from the website the version font was 2.4 and download the font from GitHub repo the version was 3.2.
> 
> I checked today and the versions are equal on the website and in the GitHub repo. Would you happen to know what version you installed the Nerdfont?
> 
> I have some issues with the missing Fonts because of this version difference.

I did not download from the web page, i cloned the git repo and patched the fonts myself and they render well when i use tmux or neovim normally so thats not a problem ig.
