### ISSUE TITLE
Configuration doesn't appear in list if using `~` as path

### ISSUE THREAD

**Issue by StraightOuttaCrompton** [joshmedeski/sesh#104]
### What happened?

When using the following configuration

```
[[session]]
name = "Home 🏡"
path = "~"
startup_command = "lf"
```

The item does not display in the list.

Workaround for reference is to use the home path from the root dir (eg `/Users/username` on mac).

### Version

1.1.0

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

Thanks for the cli man 🙏

**Comment by StraightOuttaCrompton** [comment]
I take it back. Seems to be working now 🤷

**Comment by joshmedeski** [comment]
I might have messed with it in a recent patch, glad it's working!
