### ISSUE TITLE
Trailing slash in path session config breaks startup_script/command

### ISSUE THREAD

**Issue by rtalexk** [joshmedeski/sesh#109]
### What happened?

When the `path` key in the `sesh.toml` config file, for a given session, contains a slash (`/`) at the end, the startup command/script does not get executed.

https://github.com/joshmedeski/sesh/assets/16341644/3ac9eb27-f0ef-4b13-9e4a-681cab4cb3ba

### Version

sesh version dev

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by joshmedeski** [comment]
I released `v.1.1.1` which supports trailing slashes. Thanks for reporting this!

https://github.com/joshmedeski/sesh/releases/tag/v1.1.1
