### ISSUE TITLE
Error when no Zoxide

### ISSUE THREAD

**Issue by alcb1310** [joshmedeski/sesh#11]
Wanted to test sesh on my mac, installed using the `brew install joshmedeski/sesh/sesh` as described in the README., I have no Zoxide installed.

- When executing the `sesh list` command, I get the following error:

<img width="469" alt="Screenshot 2024-01-16 at 15 02 53" src="https://github.com/joshmedeski/sesh/assets/97707578/3d13c5e5-2c54-48db-86ed-728268dbd240">

- When executing the `sesh ch`command, I get the following error:

<img width="384" alt="Screenshot 2024-01-16 at 15 05 00" src="https://github.com/joshmedeski/sesh/assets/97707578/a86af319-448c-4d96-998f-6070bc99fa37">

**Expected behavior**

Even if I do not have Zoxide installed, I should be able to use this tool, or it should give me the option  (or instructions) to automatically install it

**Comment by joshmedeski** [comment]
Thanks for flagging this, I can make sure zoxide silently fails if it fails.

**Comment by joshmedeski** [comment]
Alright, run the following command and sesh will work without zoxide:

```sh
brew update && brew upgrade sesh
```
