### ISSUE TITLE
`brew install` fails with Xcode v14

### ISSUE THREAD

**Issue by kristoferfannar** [joshmedeski/sesh#122]
### What happened?

This is hardly a bug report, but it seems that installing sesh through homebrew is not possible for my Xcode version.

I wonder why that's the case. If it is necessary, I think including it somewhere in the docs could be useful.

Below is a screenshot of my error 

<img width="1000" src="https://github.com/joshmedeski/sesh/assets/68929760/7ec6a75f-3327-4c65-8af2-843b6fbe5ec7">

### Version

N/A

### Relevant log output

see image above

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [x] I have read the documentation and understand how sesh works before submitting this bug

**Comment by kristoferfannar** [comment]
On further inspection, this may be homebrew related. Nevermind

**Comment by joshmedeski** [comment]
Yes, that appears to be a homebrew specific issue :)
