### ISSUE TITLE
sesh isn't recognized

### ISSUE THREAD

**Issue by dirad** [joshmedeski/sesh#131]
### What happened?

- Running Debian 12 [11 testing]

After installing Go, and making sure it runs fine, and displays version, and GOPATH
And after running `go install github.com/joshmedeski/sesh@latest`
Restarting.

running   `sesh list` :
```
 00:13 ❯ sesh list
bash: sesh: command not found
```

`which sesh` returns nothing.

and I can find sesh on `/usr/libexec/sudo/sesh`  -- [strange location?]

What's happening?   I dont think that folder is meant to be in the PATH.. is it?

I've tried running that file, but i actually think it isn't this sesh...!

for example: 
```
 00:19 ❯ /usr/libexec/sudo/sesh --version
/usr/libexec/sudo/sesh: unrecognized option '--version'
usage: sesh [-n] [-d directory] [-e fd] command [...]
       sesh [-cih] [-w uid:gids] file [...]
```

### Version

@latest

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by dirad** [comment]
update: 
it did get installed, but i wasnt aware of where, since there isnt any outputs about it, and its the first time im using anything GO.
so didnt know to look in `~/go` .

Running  `go install github.com/joshmedeski/sesh@latest` another time outputs nothing.   

After finding the executable in `~/go/bin/sesh`, i am able to add that folder to my path and move forward.

---

**Comment by joshmedeski** [comment]
Glad you figured it out.
