### ISSUE TITLE
Recommeded "T" script fails

### ISSUE THREAD

**Issue by dirad** [joshmedeski/sesh#132]
### What happened?

After adding recommended configs in my tmux.conf :

```
bind-key "T" run-shell "sesh connect \"$(
	sesh list | fzf-tmux -p 55%,60% \
		--no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
		--header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
		--bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c)' \
		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
		--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list)'
)\""
```

using the hotkey gives the session selection screen, however empty [using `sesh list` does list out all sessions].
After exiting [esc], im left with a displayed, in full screen, in select mode

```
'sesh connect "$(
```

### Version

sesh version dev

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by joshmedeski** [comment]
I wasn't able to recreate this issue. Does the same thing happen when you press `ctrl-c` instead of `esc`?

**Comment by dirad** [comment]
yes it does.

**Comment by dirad** [comment]
Wow this is super weird...

To troubleshoot, I made a new  tmux config folder, copied over only the tmux.conf, and restarted the server.    Tried the hotkey, and it worked fine.
I went back to the original folder, essentially the only difference is the plugins folder, so i was about to start toggling.
However the hotkey started working....... what.?

**Comment by johmsalas** [comment]
I still see this issue, seems like `run-shell` runs on a different mode:

This tmux config: `bind-key t run-shell "echo \"$PATH\""` prints out:

`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

which is not the PATH of my user

I'm wondering if it tries to run in non interactive and skips files like .bashrc or .profile

btw, I'm using MacOs, Nix and I can confirm it used to work and stopped working at some point

**Comment by johmsalas** [comment]
I think I understand the issue now. When tmux is started manuall in the terminal, it reads the env and that's the context for tmux. I recently modified it to be started automatically using Wezterm (and this is when sesh stopped working), using this in my wezterm config:

`config.default_prog = { "/opt/homebrew/bin/tmux", "new", "-A" }
`
I still don't know why, but Wezterm does not provide the environment to tmux, and that env provided during the startup is the one used for run-shell.

My solution is:
`config.default_prog = { "bash", "-l", "-c", "/usr/bin/env /opt/homebrew/bin/tmux attach || /usr/bin/env /opt/homebrew/bin/tmux" }`

My solution will probably evolve, but at least it gives you an idea.
Hope it helps people facing the same issue.

and thanks @joshmedeski for such a great DX improvement and your concise, wonderful and to the point videos
