### ISSUE TITLE
Ignore switching message after connect command

### ISSUE THREAD

**Issue by barrydevp** [joshmedeski/sesh#149]
### What would you like sesh to do?

I've just upgraded from v1 to v2 after some of the issues from v1 have been fixed. Unfortunately, my normal workflow of the tmux+fzf+sesh has been broken, as after calling connect in tmux+fzf, the switching happens with a successfully switching message that makes the tmux session not show up immediately.
[![asciicast](https://asciinema.org/a/9RaJ3VO8vm8jgcUN1ucuB15Eg.svg)](https://asciinema.org/a/9RaJ3VO8vm8jgcUN1ucuB15Eg)

**Comment by barrydevp** [comment]
I think we should add some command options, such as --silent to prevent this behavior @joshmedeski

**Comment by joshmedeski** [comment]
That's a good idea. The plan is to add logging (#140) so this message isn't really necessary.

**Comment by joshmedeski** [comment]
I'll come up with something and get it pushed.

**Comment by joshmedeski** [comment]
https://github.com/joshmedeski/sesh/releases/tag/v2.0.2

**Comment by joshmedeski** [comment]
p.s. you can remove the `-i` flag if you want to get rid of the broken icons in front of your list. Or you can set up a Nerd Font in your terminal emulator.

**Comment by barrydevp** [comment]
Thank @joshmedeski for your swift response.
My terminal works perfectly with the icon stuff. The uploaded record made by asciinema just ruins it.
