### ISSUE TITLE
Go panic for all sesh commands

### ISSUE THREAD

**Issue by bchubb-web** [joshmedeski/sesh#157]
### What happened?

When I call sesh list -t, I expected it to return a list of my current sessions but instead  a go panic happened!

this is the same for all sesh commands i run

i believe this happened after running brew upgrade, 

### Version

2.0.2

### Relevant log output

panic: couldn't unmarshal config file: "toml: cannot store a table in a slice"

goroutine 1 [running]:
github.com/joshmedeski/sesh/seshcli.App({_, _})
        /home/runner/work/sesh/sesh/seshcli/seshcli.go:44 +0xcd8
main.main()
        /home/runner/work/sesh/sesh/main.go:13 +0x4c

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by joshmedeski** [comment]
Do you have a config file? If so can you share the contents of that file?

**Comment by joshmedeski** [comment]
If you have a bad configuration I'm guessing the toml parser crashes. I could probably do something to just ignore the config if something goes wrong.

**Comment by joshmedeski** [comment]
I made an issue to improve the error message when the config fails. Not top priority but thanks for flagging it.
