### ISSUE TITLE
Session from config not showing up

### ISSUE THREAD

**Issue by albertilagan** [joshmedeski/sesh#160]
### What happened?

When I `sesh list`, I expected to see the sessions from my config first but it's not showing up.

![Screenshot 2024-09-06 at 11 34 48@2x](https://github.com/user-attachments/assets/a28daeb0-4536-4fe3-b8ef-0c97b02a714f)

### Version

2.1.0

### Relevant log output

reverting this commit seems to fix it. https://github.com/joshmedeski/sesh/commit/53121860f125ce0dcb09a0be2ac22559f1eb1d05

is this the intended default behaviour now? 

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by albertilagan** [comment]
what exactly does attached mean? does `attached` means all active sessions? or only the session that currently focused?

**Comment by joshmedeski** [comment]
Attached refers to the currently focused session. However, something went wrong with that feature and I removed it for now. So you can update to v2.1.1 and all your sessions will come back
