### ISSUE TITLE
sesh no longer shows sections active 

### ISSUE THREAD

**Issue by multivac61** [joshmedeski/sesh#169]
### What happened?

I've been using sesh now for a while and loving it. 

One of the biggest pros for me has been jumping quickly to/from sessions using the gum session command

```
bind-key "K" display-popup -E -w 40% "sesh connect \"$(
	sesh list -i | gum filter --limit 1 --placeholder 'Pick a sesh' --height 50 --prompt='⚡'
)\""
```

In the past this has shown me first the tmux sessions I have open and then a list of directories. Now it only show me the list of directories.

I'm unsure where this bug is coming from and may be related to some other program sesh depends on. 

https://github.com/user-attachments/assets/cbd7c1fb-cc1d-4073-b399-5ad20b4d51e6

### Version

2.1.0

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by multivac61** [comment]
I'm already running `sesh v2.1.0` (newest version at nixpkgs-unstable). Don't have a sesh.toml file. Any other files I could try removing?

**Comment by joshmedeski** [comment]
There was a bug in 2.1 that has been fixed with https://github.com/joshmedeski/sesh/releases/tag/v2.1.1 (and v2.1.2).

Not sure why nixpkgs hasn't updated (I'm not a nix user). But you'll need the latest version of sesh to fix this bug.
