### ISSUE TITLE
Add yay package manager

### ISSUE THREAD

**Issue by joshmedeski** [joshmedeski/sesh#173]
As an user who manages packages with yay, I want to be able to install sesh and keep it up to date.

- [x] Update goreleaser config (https://goreleaser.com/customization/aur/)
- [x] Add README.md instructions for how to install for Arch users

**Comment by alcb1310** [comment]
Hey Josh, I'd like to give this issue a try, since I've pointed to you on the stream, I would be able to test if what is done here will work correctly

**Comment by alcb1310** [comment]
Created a PR #177 for this issue, it is just a README update since goreleaser have already publish the package to the AUR using `sesh-bin` as the package name.  

[sesh aur](https://aur.archlinux.org/packages/sesh-bin)

**Comment by joshmedeski** [comment]
I'm conisdering this done, I'll work on https://github.com/joshmedeski/sesh/issues/178 to ensure it's working as expeced.
