### ISSUE TITLE
Support custom environment variables in Session configurations

### ISSUE THREAD

**Issue by DanielCardonaRojas** [joshmedeski/sesh#182]
### What would you like sesh to do?

Hey, first of all, thank you for creating this tool! 

I would like to suggest a feature enhancement that would allow users to export custom environment variables via the configuration file. The idea is to define environment variables within each session configuration, and when a session is started, these variables should be set in the environment for that session.

Proposed Change:

In addition to the current options available in the TOML configuration (like name, path, startup_command), I propose adding an option for env, where users can define one or more environment variables that will be set when the session is opened.

For example:

```toml
[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "ls"
env = { MY_CUSTOM_VAR = "downloads", ANOTHER_VAR = "example" }
```

When the session is started, the specified environment variables should be exported. This would allow external scripts or commands within the tmux session to pick up these environment variables and modify their behavior accordingly.

Benefits:

- This feature would give users more control over their environment per session.
- It allows for more dynamic setups where scripts or tools can behave differently based on the session type or context.
- Users who rely on environment variables in their workflow will find this useful for setting up tmux sessions in a more modular and automated way.

I believe this can be accomplished with: 

```sh 
tmux set-environment MY_CUSTOM_VAR "some_value"
```

**Comment by joshmedeski** [comment]
Interesting idea, would this work as-is?

```
startup_command = "MY_CUSTOM_VAR ='downloads' ANOTHER_VAR='example' ls"
```

If there are other tools like tmuxp that can do something similar I might be more interested in adding that integration rather than trying to build this kind of feature by hand.

**Comment by DanielCardonaRojas** [comment]
That doesn't seem to work. 

My second attempt was to try the following: 

```sh
startup_command = "tmux set-environment MY_CUSTOM_VAR 'some_value'"
```

The previous startup command works but only for subsequently created windows. The window that is initially created for the session does not receive the environment variable.


Investigating a bit more seems like  this would allow the first pane to receive the environment variable: 

```sh
tmux new-session -d -s my_session "export MY_CUSTOM_VAR='some_value'; exec $SHELL"
```
I believe this touches territory of `sesh connect`.  


So the final combination that yields the desired result would be: 

```sh
tmux new-session -d -s my_session "export MY_CUSTOM_VAR='some_value'; exec $SHELL"
tmux set-environment -t  my_session MY_CUSTOM_VAR 'some_value'
```

**Comment by joshmedeski** [comment]
Could you use a tool like [direnv](https://github.com/direnv/direnv)?

**Comment by DanielCardonaRojas** [comment]
I guess that could work for a very project centric workflow, however I think there are still valid escenarios where you would want environment variables tied to sessions, not directories. An obvious benefit is less planning and configuration.

**Comment by joshmedeski** [comment]
Hmm, I guess I'd like a realistic example. I've never heard anyone mention this scenario, seems overcomplicated to me (without an example).

I'm not opposed to the idea, I just don't want to add complexity to the project if I can't justify it being useful to more than one person, hope you understand that.

**Comment by DanielCardonaRojas** [comment]
I understand, and perhaps we need more specific use cases to make a solid case for why this might be beneficial. Here are some that I personally would use, though I admit that for each specific case, there might be a workaround, and maybe it’s just convenience that I’m requesting here:

- Configure a specific editor for the session with `EDITOR`.
- Choose different flavors of CLIs by changing `XDG_CONFIG_HOME`.
- Choose a different Neovim configuration for the entire session by specifying `NVIM_APPNAME`.
- Configure a Docker daemon for the entire session with `DOCKER_HOST`.
- Tweak `PATH`.
- Source different shell configurations depending on the session.


I'm sure there are probably workarounds for some of these, but I just wanted to provide some examples.

**Comment by joshmedeski** [comment]
Interesting, I think you can solve this with a startup script.

```sh
#!/bin/bash
tmux set-environment EDITOR "nano"
tmux set-environment DOCKER_HOST "localhost"
```

Then, you can call it as a custom configruation
```sh
[[session]]
name = "nano custom docker"
path = "~/projects/example"
startup_command = "nano-docker-localhost.sh"
```

Make sure the script is in your path, or define an absolute path, and make sure the file is exectuable.

I don't see why this wouldn't solve all your problems, and you can reuse the startup scripts.

Hope this helps!

**Comment by joshmedeski** [comment]
> The previous startup command works but only for subsequently created windows

I have a feeling you'll have to experiment with the script to get this to work on the first window, seems like you're trying to do something tmux isn't expecting (updating environmental variables on the fly).

**Comment by DanielCardonaRojas** [comment]
Yes, this almost does it, and is what I'm doing for now. As I mentioned in: 

https://github.com/joshmedeski/sesh/issues/182#issuecomment-2378424467

This takes care of any new windows  after the session it created  but misses on the first window.

**Comment by joshmedeski** [comment]
I was thinking the same thing (exporting and setting).

Glad we could talk it out, thanks for your feedback.

**Comment by mloskot** [comment]
I found this thread while looking for best practices on how to manage session specific environment variable to ensure it is local per session i.e. I need multiple tmux sesions each with different value of [AZURE_CONFIG_DIR](https://learn.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-file) variable.

Now, after trial and error battling with the peculiar behaviour of `tmux set/update-environment`, I realised the issue of the `window 0` what @DanielCardonaRojas mentioned in https://github.com/joshmedeski/sesh/issues/182#issuecomment-2378424467 and immediately wanted to stick `tmux new-session` in my startup scripts, but that feels indeed like _"touches territory of sesh connect"_.

Sticking `export` in the `startup_command` as in https://github.com/joshmedeski/sesh/issues/182#issuecomment-2387260913 does not seem as an elegant solution - I like mapping `startup_command` to script, then code any complexity inside the script, where the `export` seems not being effective.

I eventually found the following solution to patch environment of the pre-existing `window 0`

```bash
# Force update environment in window 0
tmux send-keys -t 0 "export FOO=foo" Enter
```

[Here is my startup script](https://github.com/mloskot/dotfiles/blob/b2e7ce06110079b127eaf35876ed3d94d37c4983/sesh/scripts/cadcorp-cloud.sh#L2-L18) which may give a more complete picture of what worked for me. I hope it helps others too. I'm not a tmux master, so I'd love to learn if it can be improved.

**Comment by joshmedeski** [comment]
Thanks for the feedback @mloskot 

I personally like using [direnv](https://direnv.net/) for setting directly specific environmental variables. That can be used with or without a session manager, you might find it to be a more simple approach.

**Comment by mloskot** [comment]
@joshmedeski Yes, `direnv` is a very useful tool and I use it as well. However, my [sesh configuration](https://github.com/mloskot/dotfiles/tree/main/sesh) manages multi-context multi-directory sessions, where the same directories can be opened by different sessions and be configured for different context e.g. 
- window 1 does `cd foo`
- window 2 does `cd bar`

and both getting the same `KUBECONFIG` set but depending on session.

Such dynamic set-up could be handled by `.envrc` too, but it still needs some env var passed from sesh  config down to `.envrc` in order to control context switching. Disadvantage of mixing sesh and direnv, IMHO, is distribution of tightly coupled environment configuration settings: some bits in sesh configs, some bits in `.envrc`. Additionally, `.envrc` need to be `.gitignore`-ed or scripted in generic way usable for others in team, and achieving that, again, needs some input controlling dynamic aspects of sessions.
