### ISSUE TITLE
Bad formatting of tmuxinator list results in missing entries when running sesh list -T

### ISSUE THREAD

**Issue by zspekt** [joshmedeski/sesh#186]
### What happened?

When I run `sesh list -T`, I expected all tmuxinator configs to be displayed, but only some of them are.

This is easily solved by passing the `--newline` (`-n`) flag to `tmuxinator list` in the `(t *RealTmuxinator) List()` method. This ensures that, other than the first line, which only contains "tmuxinator projects:", each line will be a tmuxinator config, thus making parsing easier, and more consistent.

Note that some tweaks have to be made to the parsing in order to make it fit the new format of the output.

### Version

sesh version dev

### Relevant log output

Before the minor tweaks I made:

```
$ sesh list -T
nix
nvim
obsidian
sshnixpi
sshnixth
sshopenwrt

```

After:

```
$ ./sesh list -T
nix
nvim
obsidian
sshnixpi
sshnixth
sshopenwrt
tcpLogger
thlLojjem
tmux
tmuxinator
tttest

``` 

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by joshmedeski** [comment]
@kadriandev can you fix this, please?
