### ISSUE TITLE
Reimplement clone command

### ISSUE THREAD

**Issue by joshmedeski** [joshmedeski/sesh#196]
### What happened?

The clone command (#8) currently isn't working and needs to be reimplemented with the new dependency injection pattern.

I have this command bound to the fish abbreviation, `sc` (for [S]esh [C]connect).

```sh
sesh clone --cmdDir ~/c (pbpaste)
```

Please make sure the `--cmdDir` flag works properly since that's the fastest way to clone anything from anywhere in the command line

### Version

v2.6.0

### Relevant log output

Clone command coming soon to sesh v2

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by joshmedeski** [comment]
https://github.com/garrettkrohn/treekanga/pull/17 recently did something silmiar.

**Comment by garrettkrohn** [comment]
I'll take a crack at this!
