### ISSUE TITLE
Binding for Killing a tmux Session

### ISSUE THREAD

**Issue by RiteshChepuri** [joshmedeski/sesh#21]
Add a Binding to kill tmux session from  the prompt.

**Comment by joshmedeski** [comment]
Which prompt do you mean?

If fzf, you can add something like this to the command:
```sh
sesh connect $(
	sesh list -tz | fzf-tmux -p 55%,60% \
		--no-sort --border-label ' sesh ' --prompt '⚡  ' \
		--header '  ^a all ^t tmux ^x zoxide ^f find ^d kill-session' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
		--bind 'ctrl-d:execute(tmux kill-session -t {})+reload(sesh list)'
)"
```

This is the line that's important:
```sh
		--bind 'ctrl-d:execute(tmux kill-session -t {})+reload(sesh list)'
```

**Comment by zaynOm** [comment]
I'm using the same command, when I click ctrl+d the icons disappear plus the tmux session is still there until I click the ctrl+d again

https://github.com/user-attachments/assets/4af03d60-5c4f-4505-92d6-2cc69a261069

**Comment by joshmedeski** [comment]
@zaynOm make sure to add the `--icons` flag to the reload command.
```
+reload(sesh list --icons)
```

**Comment by zaynOm** [comment]
probably there is a way to manipulate the line by removing the icon before passing it to `tmux kill-ses`

**Comment by zaynOm** [comment]
> probably there is a way to manipulate the line by removing the icon before passing it to `tmux kill-ses`

ok after some digging I found the solution.
as I said instead of passing the hole line in `tmux kill-session -t {}` we simply remove the icon like this 
`tmux kill-session -t {2..}`

for the icon to appear again add `sesh list -i` inside `reload()`

here is the full code:
```config
bind-key "J" run-shell "sesh connect \"$(
  sesh list -i | fzf-tmux -p 37%,50% --layout=reverse \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^s sessions ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
    --bind 'ctrl-s:change-prompt(🪟  )+reload(sesh list -t)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list -i)'\
)\""
```
