### ISSUE TITLE
Ability to create a session from cwd

### ISSUE THREAD

**Issue by tanishqmanuja** [joshmedeski/sesh#25]
It would be awesome if "." is kept as a reserved string and expanded to something like `sesh connect $(pwd)`

## Current Behaviour:
If used with fzf, sesh will jump to an existing dir/session with name starting ".", for example ".config" or ".local" etc etc

## Proposed Behaviour:
`sesh c .` creates a new tmux session with cwd/pwd as the root and attaches to it.

### Why reserve "." as an input ?
* One letter fuzzy finds are inherently not accurate anyways. So i wouldn't mind writing `.conf` or `.c` at minimum if i want to attach a session at .config.
* It is common for programs to work like that for example if i want to open vim at cwd, i would do `vim .` or simply `vim`

**Comment by joshmedeski** [comment]
Great idea, this makes sense to me.
