### ISSUE TITLE
Inconsistent session naming

### ISSUE THREAD

**Issue by TomDeneire** [joshmedeski/sesh#33]
I work with a large monorepo which has its git root at `/home/tdeneire/Dropbox/brocade/source`.

When I create a session in directory `/home/tdeneire/Dropbox/brocade/source/data/universe/errorhandling`, for instance, this session gets named `source/home/tdeneire/projects/brocade/source/data/universe/errorhandling`, whereas I would expect something like `source/data/universe/errorhandling`. So, it's the full, absolute path of the directory, instead of a path relative to the git root folder.

See screenshots (where you see two other examples of sessions in the same git folder).

![image](https://github.com/joshmedeski/sesh/assets/37420199/2dfd6c8e-af4b-4ed3-a23d-5863fcc2aa31)

![image](https://github.com/joshmedeski/sesh/assets/37420199/bb39c04f-70ed-4143-9b16-cbf745aff05c)

It also happens in another repo:

![image](https://github.com/joshmedeski/sesh/assets/37420199/29c2740f-202a-4aa2-9c09-a80f5f691639)

At first, I suspected it might have something to do with the fact that these directories have symlinks:

`/home/tdeneire/projects/brocade` => `/home/tdeneire/Dropbox/brocade`
`/home/tdeneire/projects/websites` => `/home/tdeneire/Dropbox/websites`
`/home/tdeneire/projects/code` => `/home/tdeneire/Dropbox/code`

But there are other directories that are in similar directories that are named just fine:

![image](https://github.com/joshmedeski/sesh/assets/37420199/fdca187e-4eea-4a88-937c-06515503ce30)

**Comment by joshmedeski** [comment]
The culprit here is symlinks. I'll start working on supporting this workflow.

**Comment by joshmedeski** [comment]
I added symbolic link support in `v0.6.2` update sesh and let me know if you get consistent session naing!

**Comment by TomDeneire** [comment]
Alas, still seeing the same problem here!

![image](https://github.com/joshmedeski/sesh/assets/37420199/84900e68-7ab5-45ef-97db-d8e3df0a601f)

**Comment by joshmedeski** [comment]
Can you clarify which folder is a symbolic link? I know if you point zoxide to the non-symlinks you'll have a decent experience for now.

**Comment by joshmedeski** [comment]
It looks like it might be:
`~/projects/code ` is a symbolic link

when you try and open `~/projects/code/subfolder` the symbolic link logic breaks

**Comment by joshmedeski** [comment]
Great! I'll mark this as resolved, glad to hear you made the switch
