### ISSUE TITLE
Custom DB

### ISSUE THREAD

**Issue by joshmedeski** [joshmedeski/sesh#37]
As a user, I want a custom database optimized for sesh, so I can use more complex features and tweak sesh to my needs. 

Zoxide is great in principle, but it's not optimized for sesh. It's optimized for zoxide. I want to be able to use sesh to its full potential, and that means a custom database.

Here are some ideas:
1. Use sqlite to support more complex features
2. Store a folder's path, session name, and score in the database, so it doesn't have to be calculated every time
3. Allow for grouping of sessions by metadata
4. Customizing the scoring algorithm to better fit how sesh is used
5. Avoid having to `cd` into a folder to add it to the database (or add a `sesh add` command?)

I'm sure the community will have other ideas as well, but I think the flexibliity and power of a custom database will be a huge step forward for sesh.

**Comment by AgusDOLARD** [comment]
are you planning to deprecate zoxide in the future?

**Comment by joshmedeski** [comment]
That would be the goal if I move forward with this issue, for now it's a wishlist item.

**Comment by AgusDOLARD** [comment]
i’m working on it

**Comment by joshmedeski** [comment]
Start with the basics, I don't want you to spend a long time in development only for us to not merge it. So let's break down the most basic way of swapping this in optionally (as a session.list source for now)

**Comment by joshmedeski** [comment]
Based off experimentation we are going to abandon this feature right now.
