### ISSUE TITLE
Icon Support (Nerd Font / Emoji)

### ISSUE THREAD

**Issue by joshmedeski** [joshmedeski/sesh#38]
As a developer, I want my session list to incline icons, to make this tool more visually appealing and make it easier to scan.

- Add config for using icons
- Add config for what icon is used for which source (tmux / zoxide)

**Comment by joshmedeski** [comment]
Waiting for #7 to be merge.

**Comment by joshmedeski** [comment]
Considering this done for now with the `-i` flag

**Comment by tanishqmanuja** [comment]
Hey @joshmedeski, I guess escaping might not be working for all terminal emulators or I am doing something wrong.

![image](https://github.com/joshmedeski/sesh/assets/40914272/49f479a2-398b-43d3-80dc-211f9bcd5a9f)

Env:
Win 11
Ubuntu WSL2
Windows Terminal
Zsh
