### ISSUE TITLE
Feature request: UI to establish first connection

### ISSUE THREAD

**Issue by TomDeneire** [joshmedeski/sesh#47]
With the previous `t` script, you could just start from scratch by opening a terminal and entering `t`. This then gave you a list of possible directories (I presume these came from zoxide?) which you could choose from to start a tmux session.

With `sesh`, this seems to be lacking. I find myself starting the day by doing something like this:

```
cd /home/tdeneire/tmp
sesh connect .
```

and then hitting leader+T to get the zoxide directory options.

It would be nice to have something like `sesh start` (which one could alias to something short like `t`) that offered a similar UI as before...

Or am I missing something in the existing functionality?

**Comment by joshmedeski** [comment]
This is up to you now, you can create an alias to achieve a similar result.

```sh
alias t="session connect (session list | fzf)
```

Feel free to adjust it to your exact needs.

**Comment by TomDeneire** [comment]
Thanks, that's what I was looking for.
