### ISSUE TITLE
Can't find a particular session

### ISSUE THREAD

**Issue by floriankimmel** [joshmedeski/sesh#52]
There is on tmux session that is not listed by sesh. It is called "Aufnahmen", which is german for recording.

I have setup sesh in tmux like that:
```
bind-key T run-shell "sesh connect $(
        sesh list -t | fzf-tmux -p 55%,60% \
        --no-sort --border-label ' sesh ' --prompt '🪟  ' \
        --header '  ^a all ^t tmux ^x zoxide ^f find' \
        --bind 'tab:down,btab:up' \
        --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
        --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
        --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
        --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)'
        )"
```
If i run `tmux ls` I do get the following output
<img width="850" alt="image" src="https://github.com/joshmedeski/sesh/assets/76724723/ab9f862d-cac9-43be-a2a4-72f002b69e2f">
The third session is output
If i run `sesh list -t` I get
<img width="382" alt="image" src="https://github.com/joshmedeski/sesh/assets/76724723/8661b24b-958a-4f72-977b-a81cc37846a7">
The session I am in is called `dotfiles`. If you need more information please reach out

I am running sesh version 0.7.2

**Comment by floriankimmel** [comment]
I deleted the session manually and wanted to recreate it. The only way I made that work was by not having a blank or any special character in my path. After removing all of those I could create the "Aufnahme" Session again

**Comment by joshmedeski** [comment]
Can you tell me what the directory was named before removing special characters and/or blanks?

We may just need to update the tool that converts directory names to valid session names.

**Comment by floriankimmel** [comment]
> Can you tell me what the directory was named before removing special characters and/or blanks?
> 
> 
> 
> We may just need to update the tool that converts directory names to valid session names.

Spaces and dashes. Like I said in the other issue. Removing those helped.

**Comment by joshmedeski** [comment]
Thanks for clarifying, I recommend using sesh to create sessions.
