### ISSUE TITLE
Not able to switch to a session to a particular session

### ISSUE THREAD

**Issue by floriankimmel** [joshmedeski/sesh#53]
<img width="382" alt="image" src="https://github.com/joshmedeski/sesh/assets/76724723/a906a968-6ab1-4fd1-8568-6347a7980b07">

These are my sessions listed by sesh. If i want to switch to the session "laufendentdecken-cli" it's not possible

<img width="217" alt="image" src="https://github.com/joshmedeski/sesh/assets/76724723/e050d67d-7a70-4192-97e7-76741427a132">

If i use `tmux-nerd-font-window-name` it works. I thought it might be the special character, but that one works.

I am currently running sesh 0.7.2

**Comment by floriankimmel** [comment]
Deleeting and recreating the "laufendentdecken-cli" session made it work again 🤷

**Comment by joshmedeski** [comment]
Can you be specific with what special characters are in that directory?

**Comment by floriankimmel** [comment]
> Can you be specific with what special characters are in that directory?

Spaces and dashes. I removed all of those and it afterwards it worked
