### ISSUE TITLE
brew not installing latest version, stuck at 0.6.1

### ISSUE THREAD

**Issue by crizzy9** [joshmedeski/sesh#56]
Trying to install sesh at the latest version of 0.8.0 via brew but it only recognizes latest version as 0.6.1

Reinstall also seems to be giving the same version. Also tried building from source but that also failed

![Screenshot 2024-01-25 at 23 28 16](https://github.com/joshmedeski/sesh/assets/8688971/0bbf5ff1-0ead-4645-984f-0596604e6193)

**Comment by joshmedeski** [comment]
Please run brew update first and see if that fixes it
