### ISSUE TITLE
Refactor the list func from the session package

### ISSUE THREAD

**Issue by AgusDOLARD** [joshmedeski/sesh#60]
Refactor the list func from the session package:

- return a []Session
- use interfaces instead of the Src struct

``` go
List(o Options, source ...Source) []string
```

**Comment by AgusDOLARD** [comment]
the tmux and zoxide will also need refactoring to fit the requirements

**Comment by joshmedeski** [comment]
This will help with #38, feel free to get started.

**Comment by joshmedeski** [comment]
I've changed the code enough that I'd consider this ticket done.
