### ISSUE TITLE
Error connecting to tmux session

### ISSUE THREAD

**Issue by AgusDOLARD** [joshmedeski/sesh#62]
# Repro
## Command run

``` sh
sesh connect $(sesh list -tz | fzf)
```

## Error
``` sh
2024/01/31 19:37:57 unable to connect to "~/projs/sesh": no tmux session found with name or path matching "~/projs/sesh"
stat /home/agus/~/projs/sesh: no such file or directory
```

**Comment by TomDeneire** [comment]
Can confirm this behaviour on my system after pulling the latest version of the repo

**Comment by joshmedeski** [comment]
@AgusDOLARD are you running `v0.9.0` or off of main?

I have some work to do before releasing another version since #57 got merged.

**Comment by AgusDOLARD** [comment]
the latest release using the go install command

**Comment by markfeinstein** [comment]
@AgusDOLARD can you try it with the latest commit?

**Comment by joshmedeski** [comment]
As of right now I'm not going to guarantee the latest commit is always stable, I'm currently working through some directory related stuff right now.

When the latest version gets released I intend on fixing this issue, thanks for letting me know!

**Comment by joshmedeski** [comment]
Can you guys install the latest version of sesh and let us know if the same issue is still there?

```
go install github.com/joshmedeski/sesh@HEAD
```

**Comment by AgusDOLARD** [comment]
seems fixed (:
