### ISSUE TITLE
fzf version

### ISSUE THREAD

**Issue by TomDeneire** [joshmedeski/sesh#63]
Hey Josh, 

I changed something in my` $PATH` yesterday, which caused `/usr/bin/fzf` to be detected before my own version `~/bin/fzf`. 

This broke sesh. 

Apparently, the first was an old version (like 0.22) (but the one installed by `apt`!), which does not work with `sesh`. After removing that binary and having `fzf` 0.44 detected on `$PATH` again, everything worked fine. 

Long story short: you might want to say something about the `fzf` version as a dependency for `sesh`?

**Comment by joshmedeski** [comment]
What command did you try and run?

**Comment by TomDeneire** [comment]
When i pressed leader-T (so executing `sesh connect $(sesh list -tz | fzf-tmux ...` I didn't get the selection UI, but just a quick flash of its border line but nothing else.

**Comment by joshmedeski** [comment]
Make sure you're using the latest version of fzf, feel free to simplify the command. I think the border label and possibly `-p` have changed in recent versions.
