### ISSUE TITLE
Issue on creating session using provided script.

### ISSUE THREAD

**Issue by kuzyo** [joshmedeski/sesh#64]
Thank for great cli app.

Using provided script that I have pasted in `tmux.config` seeing tmux popup window and able to search folders using fd, but after clicking enter on selected result app crashes, same is happening when I'm trying to select existing session.

I'm using fish shell and alacrity as terminal.

Could you please suggest any fix. Appreciate any help.

<img width="1680" alt="Screenshot 2024-02-03 at 22 19 44" src="https://github.com/joshmedeski/sesh/assets/3974101/0b548bf8-a188-4ed6-bfeb-f5e22ba106df">
<img width="860" alt="Screenshot 2024-02-03 at 22 19 57" src="https://github.com/joshmedeski/sesh/assets/3974101/8edd463e-3556-448f-b73f-6ed8cc691c6a">

**Comment by joshmedeski** [comment]
Do you have zoxide set up?

**Comment by kuzyo** [comment]
yes, have zoxide and it shows results in popup window.

**Comment by kuzyo** [comment]
Initially thought issue with wrong syntax, but seeing that you actually to using fish. BTW installed sesh using brew.

**Comment by joshmedeski** [comment]
Okay, can you try running `sesh connect {result}` and tell me the exact error message? Unfortunately fzf doesn't do a good job presenting the actual error to the user.

I'm releasing a new version now so we'll see if that improves your experience.

**Comment by kuzyo** [comment]
Interesting that `sesh connect {result}` command is working correct. I even can select correct session in tmux pane with such command
```
❯ sesh connect $(sesh list -tz | fzf-tmux -p 55%,60%)
```

<img width="1042" alt="Screenshot 2024-02-04 at 13 40 13" src="https://github.com/joshmedeski/sesh/assets/3974101/d05ff659-7da8-47db-86e4-52d16dd45bf3">

But it doesnt work for me when I have same one in tmux config.

```
bind-key "T" run-shell "sesh connect $(sesh list -tz | fzf-tmux -p 55%,60%)"
```

<img width="1164" alt="Screenshot 2024-02-04 at 13 43 15" src="https://github.com/joshmedeski/sesh/assets/3974101/279ed3d6-a390-41b5-859d-e9af30cb2573">

**Comment by kuzyo** [comment]
Used such command to have some logs
```
bind-key "T" run-shell "echo 'Before FZF'; sesh list -tz; echo 'After FZF'; sesh connect $(sesh list -tz 2>&1 | fzf-tmux -p 55%,60% > /tmp/fzf_tmux_log)"
```
logs:
```
sh: sesh: command not found
```



<img width="1091" alt="Screenshot 2024-02-04 at 13 51 27" src="https://github.com/joshmedeski/sesh/assets/3974101/2df8fbce-5cad-4eb8-9d59-b253d250c97b">

**Comment by kuzyo** [comment]
Sorry for confusion, long debugging session, but I have to just reload my machine and everything started working as expected.

**Comment by joshmedeski** [comment]
Glad you got it figured out, sesh is a work-in-progress so let me know if anything else comes up.

**Comment by kuzyo** [comment]
Thank you, definitely will do. Full work day without any issues. Went ahead and replaced ThePrimeagen tmux-sessionizer that I have used for the same purpose.
