### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by joshmedeski** [joshmedeski/sesh#7]
As a user, I want to create a config file, so I can customize my sesh experience.

- `~/config/.sesh/sesh.yml` file (or toml?)
- Add session name formatting (ex: include parent directory)

**Comment by tanishqmanuja** [comment]
- Add default repos dir to config (so that it will be used if --cmdDir is not set)

**Comment by joebonneau** [comment]
commenting for assignment!

**Comment by qrockz** [comment]
@joshmedeski what purpose has the **name** key in the **toml** file? Is it more like a description/comment of a session? Because changing it has no effect on anything (tmux session name, fzf listed sessions).

**Comment by joshmedeski** [comment]
@qrockz here is what the `name` key does for custom session configurations:
1. It will be used when listing configs (`sesh list -c`)
2. It will be used as the tmux session name when passed into the connect function (`sesh connect "config name")
