### ISSUE TITLE
Fix script in the readme

### ISSUE THREAD

**Issue by PbVrCt** [joshmedeski/sesh#70]
I had some problems getting this script to work:
 ```
 bind-key "T" run-shell "sesh connect $(
	sesh list -tz | fzf-tmux -p 55%,60% \
		--no-sort --border-label ' sesh ' --prompt '⚡  ' \
		--header '  ^a all ^t tmux ^x zoxide ^f find' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)'
)"
```

Here's how I fixed them:
- Problem 1: Initially the popup window was exiting automatically. I was able to open it with...
```
sesh connect $(sesh list -tz | fzf-tmux -p 55%,60%)
```
...but not with the full script, until I removed this option:
```
--border-label 'sesh'
```
I am using zsh. I had the problem in both Alacritty and foot.

- Problem 2: The binded commands where returning "Command not found". Problem was I was calling the script from tmux and sesh, which I had installed locally, was not in path.
I replaced: ```sesh``` for  ```$HOME/go/bin/sesh```
And added: ```export PATH="$HOME/.cargo/bin:$PATH"``` for zoxide to be in path, otherwise ```sesh connect``` would complain that it was not in path.

- Problem 3: ```fd``` did not seem to be installed in my computer. Turns out in Ubuntu fd-find is installed as ```fdfind``` instead of ```fd```, to avoid a clash name with other existing utility.
I replaced: ```fd``` for  ```fdfind```

After applying those changes I got this working:

tmux.conf
```
bind "T" run-shell "~/.config/scripts/tmux/sessionizer.sh"
```

sessionizer.sh:
```
#!/bin/bash
export PATH="$HOME/.cargo/bin:$PATH"
$HOME/go/bin/sesh connect $(
	$HOME/go/bin/sesh list -tz | fzf-tmux -p 55%,60% \
		--no-sort --prompt '⚡  ' \
		--header '  ^a all ^t tmux ^x zoxide ^f find' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡  )+reload($HOME/go/bin/sesh list)' \
		 --bind 'ctrl-t:change-prompt(🪟 )+reload($HOME/go/bin/sesh list -t)' \
		--bind 'ctrl-x:change-prompt(📁  )+reload($HOME/go/bin/sesh list -z)' \
		 --bind 'ctrl-f:change-prompt(🔎 )+reload(fdfind -H -d 2 -t d -E .Trash . ~)'
)
```

Thank you for making this software. Looking forward to its final version.

### Version

❯ sesh --version sesh version dev

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by joshmedeski** [comment]
Hey @PbVrCt, thanks for the feedback.

1. The `--border-label 'sesh'` is related to using an older version of fzf, if you upgrade to the latest version that feature will work
2. I highly recommend adding `$HOME/go/bin` to your path, not a requirement but makes it easier when interacting with sesh in general.
3. `fd` is just an example. You can create any `find` command that works for you as a fallback if you don't have a record stored in zoxide yet and want to start a new session from the fzf tmux popup.

I hope that helps, I'm not going to update the README but if someone else runs into these issues hopefully this feedback will help.

**Comment by PbVrCt** [comment]
Hi @joshmedeski, yes it helps, thank you.

Regarding 2. , I have ```$HOME/go/bin``` in path, but tmux is not getting the same paths as my default shell.

Anyways, the problem is solved. Thanks!

**Comment by qrockz** [comment]
@joshmedeski @PbVrCt where did you store fzf-tmux so that you can access it gobally?
Did you create a sym link to tmux/plugins/tmux-fzf/scripts/.fzf-tmux or an alias in .bashrc which points to .fzf-tmux or did you copy .fzf-tmux to /usr/local/bin/fzf-tmux ?

I'm just curios because this script:
```
bind-key "T" run-shell "sesh connect \"$(
	sesh list -tz | fzf-tmux -p 55%,60% \
		--no-sort --border-label ' sesh ' --prompt '⚡  ' \
		--header '  ^a all ^t tmux ^x zoxide ^d tmux kill ^f find' \
		--bind 'tab:down,btab:up' \
		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
		--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list)'
)\""
```
does requiere fzf-tmux to be globally accessible and I want to know a smart way to do so :D

**Comment by PbVrCt** [comment]
> @joshmedeski @PbVrCt where did you store fzf-tmux so that you can access it gobally? Did you create a sym link to tmux/plugins/tmux-fzf/scripts/.fzf-tmux or an alias in .bashrc which points to .fzf-tmux or did you copy .fzf-tmux to /usr/local/bin/fzf-tmux ?
> 
> I'm just curios because this script:
> 
> ```
> bind-key "T" run-shell "sesh connect \"$(
> 	sesh list -tz | fzf-tmux -p 55%,60% \
> 		--no-sort --border-label ' sesh ' --prompt '⚡  ' \
> 		--header '  ^a all ^t tmux ^x zoxide ^d tmux kill ^f find' \
> 		--bind 'tab:down,btab:up' \
> 		--bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list)' \
> 		--bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t)' \
> 		--bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z)' \
> 		--bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
> 		--bind 'ctrl-d:execute(tmux kill-session -t {})+change-prompt(⚡  )+reload(sesh list)'
> )\""
> ```
> 
> does requiere fzf-tmux to be globally accessible and I want to know a smart way to do so :D

I did not do none of those 3 options. The only thing I did with fzf-tmux is install it with the tmux plugin manager. Revelant part of my `tmux.conf` :
```
set -g @tpm_plugins '             \
  tmux-plugins/tpm               \
  tmux-plugins/tmux-sensible     \
  tmux-plugins/tmux-resurrect    \
  tmux-plugins/tmux-continuum    \
  sainnhe/tmux-fzf               \
'

set -g @resurrect-save 'C-s'
set -g @resurrect-restore 'C-r'
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '1'

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'
# Keep this line at the very bottom
run '~/.tmux/plugins/tpm/tpm'
```

**Comment by joshmedeski** [comment]
`fzf-tmux` was installed to `/opt/homebrew/opt/fzf/bin/fzf-tmux` when I setup fzf on my mac. See [fzf](https://github.com/junegunn/fzf) to see how it needs to be installed on your OS.

**Comment by qrockz** [comment]
Yeah, I think I've downloaded only the fzf binary and did not have used the package installer.
With the package installer, in my case apt, there comes extra stuff like fzf-tmux.

Thx guys.
