### ISSUE TITLE
Custom session names

### ISSUE THREAD

**Issue by bchubb-web** [joshmedeski/sesh#77]
### What would you like sesh to do?

I use sesh to switch between different codebases, but the folder i work in uses an arbitrary directory name rather than the project name, it would be useful to be able to set a function which is called, passing the full path as a param, and the result would be the session name

**Comment by joshmedeski** [comment]
Give me some time to get this done. I have to rearrange the session determining logic. I think it's reasonable to just have sesh match the session based off the session name instead of the path of the session (which is what it's doing now).

**Comment by joshmedeski** [comment]
@bchubb-web sesh can now connect to custom session names, download `v0.14.0`, test it out, and let me know how it works for you
