### ISSUE TITLE
[Package request] Nix

### ISSUE THREAD

**Issue by delabere** [joshmedeski/sesh#79]
If you could add a flake.nix to this project that would be awesome!

**Comment by joshmedeski** [comment]
There's a PR up right now, waiting for it to get merged:
https://github.com/NixOS/nixpkgs/pull/286594

**Comment by joshmedeski** [comment]
The nxpkgs PR (see last comment) has been merged! Please let us know it it isn't working as expected.

**Comment by delabere** [comment]
It's working great! Thanks for the awesome plugin and for making it nix compatible!

**Comment by meicale** [comment]
It is kind of wired. I can install sesh using nix-shell but my nixpkgs from nix/homemanager can not find the sesh value. Error msgs:
```
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:9:12:
            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|

       … while evaluating derivation 'home-manager-generation'
         whose name attribute is located at /nix/store/4fgs7yzsy2dqnjw8j42qlp9i1vgarzy0-sourc
e/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'buildCommand' of derivation 'home-manager-generation'
         at /nix/store/4fgs7yzsy2dqnjw8j42qlp9i1vgarzy0-source/pkgs/build-support/trivial-bui
lders/default.nix:87:15:
           86|       enableParallelBuilding = true;
           87|       inherit buildCommand name;
             |               ^
           88|       passAsFile = [ "buildCommand" ]

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: undefined variable 'sesh'
       at /nix/store/p3rd8nvgzpzdmfg13h4h2lvaqw2pmvr0-source/nix/home-manager/home.nix:74:5:
           73|     # session mangaer baseon tmux
           74|     sesh
             |     ^
```
Thank you!

**Comment by adgai19** [comment]
As of today, sesh is in `nixos-unstable`. You might be using home manager which is on `nixos-23.11`. If that is the case, you will have to either move to unstable or install this one package from unstable.

**Comment by meicale** [comment]
Thank you for your reply!
I use nix/homemanager in wsl/ubuntu24.04. My nix pkgs is unstable.

**Comment by meicale** [comment]
> Thank you for your reply! I use nix/homemanager in wsl/ubuntu24.04. My nix pkgs is unstable.

The most wired thing is that I can install it successfully using `nix-shell -p`
