### ISSUE TITLE
Clone Command

### ISSUE THREAD

**Issue by joshmedeski** [joshmedeski/sesh#8]
As a developer, I want to quickly clone and create a session all in one step, so I can be more efficient.

- Include `--cmdDir` flag

**Comment by joshmedeski** [comment]
See https://github.com/joshmedeski/t-smart-tmux-session-manager/issues/100

**Comment by joshmedeski** [comment]
More to do:
- Show cloning stdout so the user sees progress
- Support `owner/repo` to clone with the gh CLI (if installed)
- Add unit tests (integrated with git)

**Comment by tanishqmanuja** [comment]
Passing I/O between cmnds

```go
cmd := exec.Command(.....)

cmd.Stdin = os.Stdin // probably shouldn't be needed for this use-case
cmd.Stdout = os.Stdout
cmd.Stderr = os.Stderr
cmd.Env = os.Environ()

err := cmd.Run()
// error handling here...
```

Might do a PR if I get time.
