### ISSUE TITLE
Add tmuxp support

### ISSUE THREAD

**Issue by kohane27** [joshmedeski/sesh#87]
### What would you like sesh to do?

Hello there! Thank you for creating `sesh` and the previous `t-smart-tmux-session-manager`!

I'm trying to migrate from `t` to `sesh` but facing the following problem.

## Description

I'm using [tmuxp](https://github.com/tmux-python/tmuxp) to `fzf` find and load `tmux` sessions:

```bash
tmuxp load -d $(ls ~/.config/tmuxp | fzf)
```

The following is extracted from my modified `t`:

```bash
# check if selection is in is TMUXP
WORKSPACE_NAME=$($TMUXP_LS | grep "$RESULT")
if [ ! -z "$WORKSPACE_NAME" -a "$WORKSPACE_NAME" != " " ]; then
    $TMUXP_PATH load -d "$WORKSPACE_NAME" >/dev/null 2>&1
    tmux switch-client -t "$WORKSPACE_NAME"
    exit 0
fi
```

I'm hoping `sesh` would have the following:

1. custom directories, i.e., `sesh list ~/.config/tmuxp`
2. custom command, i.e., `tmuxp load -d`

Such that I can use the following:

```bash
sesh $CUSTOM_COMMAND "$(sesh list $CUSTOM_DIR | fzf-tmux -p 55%,60%)"
```

I understand that this may be out of project scope. I hacked on the original `t` because it's a bash script, but I'm not sure about golang.

Thank you again!

**Comment by joshmedeski** [comment]
Hi @kohane27 thanks for the suggestion. I think integrating with tmuxp is possible.

Would you want non-tmuxp commands to still work (ex: listing existing sessions and attaching to current tmux sessions). If so, we'll probably need to adjust your suggestions to better work alongside existing functionality (rather than replacing it).

I've got some ideas but please clarify how you'd expect this to work alongside the current features sesh has to offer.

- Would you want to list tmux sessions, zoxide results, and tmuxp configs at the same time?
- Would you want to conditionally load tmuxp configs if the session already exists or there is not config file that matches the result?

**Comment by joshmedeski** [comment]
I'd prefer to keep the connect command as-is, and extend it's functionality.

I think this approach could work:

```toml
[[session]]
name = "dotfiles"
path = "~/c/dotfiles"
tmuxp_config = "~/.config/tmuxp/dotfiles.yaml"
```

We could update the session config over time to offer different options, like tmuxinator as well.

```toml
[[session]]
name = "dotfiles"
path = "~/c/dotfiles"
tmuxinator_config = "~/.config/tmuxinator/dotfiles.yaml"
```

Do you like this approach? Then, sesh connect would be the same, and when you chose a path that matches a config, it would detect the config and run it.

**Comment by kohane27** [comment]
Hello @joshmedeski

Apologies for my late reply.

Thank you for the suggestion:) I think this approach of yours is cleaner!

I'm looking forward to testing when you have time to implement this feature. Thank you again!

**Comment by jonykalavera** [comment]
Quick workaround if you use `.tmuxp.yaml` files, at your sesh config dir:

```bash
$ cat sesh.toml
[default_session]
startup_script="~/.config/sesh/startup_script.sh"

$ cat startup_script.sh
#!/bin/bash
[[ -e ".tmuxp.yaml" ]] && tmuxp load -a .
```

**Comment by joshmedeski** [comment]
That works! For now I prefer being able to just call any arbitrary script. We can think more about adding specific integrations after v2 ships.

**Comment by albertilagan** [comment]
> Quick workaround if you use `.tmuxp.yaml` files, at your sesh config dir:
> 
> ```shell
> $ cat sesh.toml
> [default_session]
> startup_script="~/.config/sesh/startup_script.sh"
> 
> $ cat startup_script.sh
> #!/bin/bash
> [[ -e ".tmuxp.yaml" ]] && tmuxp load -a .
> ```

should have done a quick search before doing it myself :D sortof have the same approach, only reason I didn't do it like you did is I don't wanna impose certain layout structure on my co-worker hence I didn't add it on a repo level but instead put it on my dotfiles/sesh layout folder (unless ofc you make your .tmuxp.yaml gitignored, I might consider that setup actually.)

![image](https://github.com/user-attachments/assets/59a6479c-8a53-4623-bc22-4c698371bd8e)
![image](https://github.com/user-attachments/assets/bc6eb448-7bce-4217-a762-2bb51379afc8)

**Comment by albertilagan** [comment]
would be nice if anyone can tell me how to apply it on active session which is `-a` and not have the default window opened by sesh/tmux so I don't have to do this ` && tmux kill-window -t 1` anymore, haven't look into `tmuxp` docs indepth so maybe there's something there,

**Comment by joshmedeski** [comment]
@albertilagan tmuxinator is integrated in sesh now, so now you can simply convert your dotfiles and luxor-apps tmuxp configs to tmuxinator and you don't have to provide any custom sesh configs.

Hope that help.

**Comment by joshmedeski** [comment]
@kohane27 since tmuxp doesn't have an official `list` command I'm not going to officially integrate it into sesh, however, I hope to one day provide the ability to add custom providers to sesh, but I think it will require the #202 to allow for a more programatic approach to the session picker (fzf-like pickers are very limiting).

**Comment by jonykalavera** [comment]
> (unless ofc you make your .tmuxp.yaml gitignored, I might consider that setup actually.)

That's exactly what I do.

**Comment by phanirithvij** [comment]
it is `startup_command` now, I was scratching my head why `startup_script` wasn't working.

**Comment by joshmedeski** [comment]
> it is `startup_command` now, I was scratching my head why `startup_script` wasn't working.

Yes, it was a breaking change from v1 to v2 https://github.com/joshmedeski/sesh/releases/tag/v2.0.0
