### ISSUE TITLE
Support to create sessions from SSH config

### ISSUE THREAD

**Issue by enthusiva** [joshmedeski/sesh#90]
I would like sesh also list down the SSH hosts configured in the ssh config so that I can directly create tmux sessions for SSH connections. As of now, I create empty directories for each ssh server so that sesh lists those directories for me to pick from and use startup scripts to ssh into the servers based on the empty directory path.

I really enjoy sesh a lot and it helps to speed up my dev workflow. Thank you for making this great tool.

**Comment by joshmedeski** [comment]
Can you clarify what happens when you select a configured SSH host. Would it create a local tmux session and run a ssh connect command?

I believe you'll be able to set this up with #86 when I ship that feature. If it's too limiting for you I can revisit this issue.

**Comment by enthusiva** [comment]
you are right. It will create local session and the startup script will run the ssh command to connect to the server. I will check session config feature once it is released.

**Comment by enthusiva** [comment]
@joshmedeski I migrated to the latest version of sesh recently. It seems that the path attribute should be specified for all sessions in the config. Otherwise, it executes the startup command for the first session for any session defined in the sesh.toml file.  For ex, in the below config, when I tried to run session for server2 or server3, sesh always executes the startup command for server1. 
```
[[session]]
name = "server1"
startup_command = "ssh server1"

[[session]]
name = "server2"
startup_command = "ssh server2"

[[session]]
name = "server3"
startup_command = "ssh server3"
```
If I specify the path attribute for all these sessions, it works perfectly. I am unable to conclude whether it is by design or bug. It would be better if sesh can implicitly use the home directory as default path if the path attribute is not specified for a session.

**Comment by joshmedeski** [comment]
Every tmux session is associated with a directory, wether you use it or not.

I recommend setting it to something (anything, I guess in your case it won't matter.

**Comment by joshmedeski** [comment]
Closing this issue since it appears to be dealt with using the config feature.

**Comment by Buttars** [comment]
@joshmedeski it would be nice to have an option show the available ssh servers automatically as they exist in the ssh config file at ~/.ssh/config. A nice utility that does something similar is sshs. This begs the question that maybe the categories sesh offers should be dynamic too.

**Comment by joshmedeski** [comment]
@Buttars is there a CLI that can list ssh configs? I don't really want sesh to reach too far outside of tmux sessions, and in my mind connecting to an ssh server via a startup script feels outside the scope of this project.

But I'd be willing to accept a PR or do some minor work to integrate with an existing tool.

**Comment by Buttars** [comment]
@joshmedeski https://github.com/kevinburke/ssh_config is a go utility that can parse the config file. 

I believe this is in scope for sesh because ssh commands hardly ever tie themselves to a local directory so having sesh be able to just spawn a session tied to a host is logical to me. Instead of tying a directory to a tmux session your time that's SSH host and config. 

Hope you consider it! If not I may open a PR for it if I can find the time.
