### ISSUE TITLE
sesh 1.0.1 errors if a config file doesn't exist

### ISSUE THREAD

**Issue by markfeinstein** [joshmedeski/sesh#92]
### What happened?

When I run any sesh command after upgrading to 1.0.1, I expected to not see any errors but I see errors about a missing config file in the sesh output and newly opened tmux sessions! If not config file is present sesh should silently use defaults or create a new config file with default values.

### Version

sesh version 1.0.1

### Relevant log output

Error parsing config file: parseConfigFromFile - error reading config file (/home/path/.config/sesh/sesh.toml): open /home/path/.config/sesh/sesh.toml: no such file or directory
Using default config insteadError parsing config file: parseConfigFromFile - error reading config file (/home/path/.config/sesh/sesh.toml): open /home/path/.config/sesh/sesh.toml: no such file or directory
Using default config instead
'sesh connect "$(

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by joshmedeski** [comment]
That’s fair, it should be able to work without the configuration file

**Comment by joshmedeski** [comment]
@markfeinstein it silently continues if the configuration file isn't found.
