### ISSUE TITLE
Documentation issue: Session Configuration vs Startup Script

### ISSUE THREAD

**Issue by darthmeme** [joshmedeski/sesh#94]
### What happened?

In the README, the Session Configuration and Startup Script sections have the same first paragraph. I haven't actually dived deep into `sesh` yet, but I assume that the session config replaces the old startup script stuff? I was gonna make a PR but I wasn't sure if that was the case 😅 

### Version

N/A

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by joshmedeski** [comment]
@darthmeme see the "Breaking Changes" of the release:
https://github.com/joshmedeski/sesh/releases/tag/v1.0.0

I can review the README and make sure it's more accurate, thanks for the tip.
