### ISSUE TITLE
how to configure fzf for default or reverse layout mode?

### ISSUE THREAD

**Issue by mayersj1** [joshmedeski/sesh#98]
### What happened?

I have no special config for sesh.  I'm using the sample keybinding shown in the repository.  On three of my four machines, invoking the sesh popup shows the prompt at the top.  On the fourth machine, the prompt is at the bottom of the screen.  Is there some special fzf configuration that I'm not aware of that could be different here?

### Version

dev

### Reviewed

- [X] Reviewed existing issues and made sure this bug has not already been submitted.
- [X] I have read the documentation and understand how sesh works before submitting this bug

**Comment by joshmedeski** [comment]
Look at your "FZF_DEFAULT_OPTS" and "FZF_TMUX_OPTS" variables.

Here's what I have them set to on my machine:
https://github.com/joshmedeski/dotfiles/blob/e86fff4306b584095df62e4fa3790db17e6c94de/.config/fish/conf.d/fzf.fish?plain=1#L2

**Comment by mayersj1** [comment]
That was the pointer I needed. the machine missing this variable was my work machine that has a different .zshrc and I'd fogotten about the hm-session-vars.sh sourcing that needed to happen. Working now!  Thanks!
